[core]
name:item
displayText:droppedItem
displayDescription:placeholdr
class: CustomUnitMetadata
price:0
maxHp: 65536
mass:250
techLevel: 2
buildSpeed: 0.0005
availableInDemo: false
tags:item
selfRegenRate:0.1
radius: 5
displayRadius:7
@memory stack:number
@memory id:number
@memory type:number
@memory drive:unit
ignoreInUnitCapCalculation:true
autoTriggerCheckRate:every8Frames
autoTriggerCooldownTime_allowDangerousHighCPU:true
#copyFrom:ROOT:/template/resource.template,ROOT:/template/alloy.template,ROOT:/template/invGeneral.template
createNeutral: true
#createOnAggressiveTeam: true
updateUnitMemory:drive=nearestUnit(withinRange=20,withTag="conveyor")
updateUnitMemoryRate:0.1s
autoTriggerCooldownTime:0s
[graphics]
total_frames: 1
image:ROOT:texture/UI/common/4.png
#image_wreak:ROOT:texture/unit/builder/industryEngineerW.png
image_turret: NONE
scaleImagesTo:1
#scaleTurretImagesTo: 9
#AUTO
image_shadow: ROOT:texture/UI/common/4.png
shadowOffsetX:1
shadowOffsetY:1
disableLowHpFire:true
disableLowHpSmoke:true
showHealthBar:false
[attack]
canAttack:false
[movement]
movementType: AIR
moveSpeed:1
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.1
targetHeight: 7
targetHeightDrift: 0
startingHeightOffset:25
joinsGroupFormations:false
maxTurnSpeed:0
turnAcceleration: 0.08
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:181
[hiddenAction_init]
autoTriggerOnEvent:created
setUnitMemory:stack=1
[decal_texture]
layer:onTop
onlyWhileActive:true
#pivotOffset
#stack_indexCount:1+int(select(memory.stack/3<=5,memory.stack/3,5))
#imageStack:ROOT:texture/resource/sprite/resSprite.png
image:ROOT:texture/resource/sprite/resSprite.png
total_frames:16
frame:memory.type
imageScale:1.5+(0.05*memory.stack)-(0.5/memory.stack)
#stack_hOffset:5
#stack_frameOffset:1
alwaysStartDirAtZero:true
#image_shadow:ROOT:texture/UI/common/4.png
color:#acefdb
[hiddenAction_merge]
setUnitStats:mass=10*memory.stack,hp=1+50*memory.stack
autoTrigger:if self.customTimer > 5
resetCustomTimer:true
autoTriggerOnEvent:created
#debugMessage:
takeResources:0
takeResources_maxUnits:1
#takeResources_excludeUnitsWithTheseResources:state=1
takeResources_excludeUnitsWithoutTags:item
takeResources_searchOnly:true
takeResources_triggerActionForEach:mergeRequest
takeResources_includeUnitsWithinRange:50
[hiddenAction_mergeRequest]
sendMessageTo:thisActionTarget
sendMessageWithTags:merge
sendMessageWithData:id=memory.id
[hiddenAction_mergeAcc]
autoTriggerOnEvent:newMessage(withTag="merge")
requireConditional:if eventData('id',type='number') == memory.id and eventSource != self
sendMessageTo:eventSource
sendMessageWithTags:mergeAcc
sendMessageWithData:num=memory.stack
deleteSelf:true
[hiddenAction_add]
autoTriggerOnEvent:newMessage(withTag="mergeAcc")
setUnitMemory:stack=memory.stack+eventData('num',type='number')
[hiddenAction_moveWithConv]
autoTrigger:true
buildSpeed:0
#addWaypoint_type:move
#setUnitStats:movespeed
teleportTo:self.getOffsetRelative(memory.drive.readUnitMemory('sx',type='float'),memory.drive.readUnitMemory('sy',type='float'))