[core]
name:powerGrid
#Ohno why not system
displayText:电网
displayDescription:-你他妈怎么看到这段介绍的
showInEditor:false
mass:1
radius:1
@memory new:unit
@memory member:unit[]
@memory index:number

maxHp:2147483647
selfRegenRate:2147483647
price:1
isUnselectableAsTarget:true
explodeOnDeath:false
tags:elesto
@memory power:float
@memory powerGen:float
@memory powerCost:float
@memory storageMax:float
@memory flux:float
@memory alpha:float
[graphics]
isVisible:false
scaleImagesTo:1
image:ROOT:texture/other/ne.png
image_wreak:NONE
image_turret:NONE
image_shadow:NONE
showHealthBar:false
disableLowHpSmoke:true
disableLowHpFire:true
[attack]
canAttack:false
[movement]
movementType:LAND
[hiddenAction_reg]
autoTriggerOnEvent:newMessage(withTag='reg')
shrinkArrays:member
setUnitMemory:member[memory.member.size]=eventSource


[hiddenAction_updt]
autoTriggerOnEvent:newMessage(withTag='updatePower')
setUnitMemory:powerGen=memory.powerGen+select(eventData('powerDelta',type='float')>=0,eventData('powerDelta',type='float'),0),powerCost=memory.powerCost-select(eventData('powerDelta',type='float')<0,eventData('powerDelta',type='float'),0)
alsoTriggerAction:updtA
[hiddenAction_updtA]
setUnitMemory:alpha=select(memory.powerGen>=memory.powerCost,1,memory.powerGen/memory.powerCost)
#[hiddenAction_pr]
#autoTriggerOnEvent:created
#setCustomTarget1:parent
#[hiddenAction_reunionCompare]
#autoTriggerOnEvent:newMessage(withTag='reunion')
#setUnitMemory:new=select(eventData('new',type='unit').readUnitMemory('member',type='unit[]').size<memory.member.size,self,eventData('new',type='unit')),index=0
#alsoQueueAction:reunion,selfDel
#sendMessageTo:eventData('new',type='unit')
#sendMessageWithData:ntarget=memory.new
#sendMessageWithTags:reunionC
#[hiddenAction_reunion]
#autoTriggerOnEventRecursionLimit:64
#highPriorityQueue:true
#sendMessageTo:memory.member[memory.index]
#sendMessageWithTags:reunionC
#sendMessageWithData:ntarget=memory.new
#requireConditional:if memory.index!=-1
#setUnitMemory:index=select(memory.index>memory.member.size,-1,memory.index+1)
#alsoTriggerAction:reunion
#[hiddenAction_reunionCompare2]
#autoTriggerOnEvent:newMessage(withTag='reunionC')
#setUnitMemory:new=eventData('ntarget',type='unit')
#alsoQueueAction:reunion,selfDel
#[hiddenAction_selfDel]
#buildSpeed:32s
#requireConditional:if self != memory.new
#deleteSelf=true
#deleteSelf可以直接跟动态值吗
#[hiddenAction_register]
#autoTriggerOnEvent:newMessage(withTag='registerRequest')
#setUnitMemory:member[memory.member.size]=eventSource
#shrinkArrays:member