[core]
copyFrom:ROOT:template/eleService.template
name:powerSource
displayText:测试电力源
mass:1000
radius:10
constructionFootprint:0,0,0,0
footprint:0,0,0,0
#buildingToFootprintOffsetY:20
isBuilding:true
price:2147483647
maxHp:1024
[graphics]
image:ROOT:/texture/other/none.png
scaleImagesTo:20
image_wreak:NONE
image_shadow:NONE
lock_body_rotation_with_main_turret:false
[action_inc]
buildSpeed:0.1s
text:发电
setUnitMemory:power=memory.power+10
[action_cos]
buildSpeed:0.1s
text:耗电
setUnitMemory:power=memory.power-10
[attack]
canAttack:false
[movement]
movementType:BUILDING
targetHeight:0
targetHeightDrift:0