[core]
isPickableStartingUnit:true
name:ironConveyor
displayText:铁基传送带
displayDescription:滚木
class: CustomUnitMetadata
price:wood=3
maxHp: 200
mass: 32
buildSpeed:1s
radius: 10
isBuilding:true
footprint:0,0,0,0
constructionFootprint:0,0,0,0
autoTriggerCooldownTime:0.5s
copyFrom:ROOT:/template/resource.template,ROOT:/template/conveyor.template
@global speed=22
[comment_test]
[graphics]
total_frames: 1
image:ROOT:texture/UI/common/4.png
#image_wreak:ROOT:texture/unit/builder/industryEngineerW.png
image_turret: NONE
scaleImagesTo: 1
#scaleTurretImagesTo: 9
#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
[attack]
canAttack:false
[movement]
movementType: HOVER
targetHeight: 0
targetHeightDrift: 0
[ai]
useAsBuilder: true


[decal_main]
image:ROOT:texture/machine/item/conveyor0.png