[core]
copyFrom:ROOT:template/eleNode.template
name:copperNode
displayText:铜电线桩
displayDescription:-最大5连接

maxHp:150
price:100
shieldDisplayOnlyDeflection:true
mass:1000
radius:10
constructionFootprint:0,0,0,0
footprint:0,0,0,0
#buildingToFootprintOffsetY:20
isBuilding:true
[graphics]
scaleImagesTo:20
image:ROOT:texture/energy/electric/node/smallNodeWire.png
image_wreak:NONE
image_shadow:NONE
lock_body_rotation_with_main_turret:false
[attack]
canAttack:false
[movement]
movementType:BUILDING
targetHeight:0
targetHeightDrift:0