[core]
name:tree
displayText:树
displayDescription:一棵普通的树
class: CustomUnitMetadata
price:wood=12
maxHp: 160
mass: 150
techLevel: 2
buildSpeed:16.6s
availableInDemo: false
tags:plant,resource
selfRegenRate:0.5
radius: 10
isBio:false
isBuilder:true
copyFrom:ROOT:/template/resource.template
[graphics]
total_frames: 1
image:ROOT:texture/resource/nature/wtfTree.png
image_wreak:NONE
#ROOT:texture/unit/builder/industryEngineerW.png
image_turret: NONE
scaleImagesTo:20
#scaleTurretImagesTo: 9
#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
[attack]
canAttack:false
[movement]
movementType:BUILDING